name: GitHub Sync Upstream Release
description: Get latest upstream release, rebase on top and push the dd release tag
author: antoine.gaillard@datadoghq.com

inputs:
  upstream_repo:
    description: Upstream repo
    required: true
  datadog_branch:
    description: Branch name that contains our patches
    required: false
    default: datadog
  base_tag:
    description: Tag used to mark the base
    required: false
    default: last-dd-base

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Setup git config
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --local user.password ${GITHUB_TOKEN}
    - name: Setup remotes
      shell: bash
      run: |
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git remote add upstream https://github.com/${{ inputs.upstream_repo }}
    - name: Fetch upstream tags
      shell: bash
      run: git fetch upstream --tags
    - name: Get latest tags
      id: get_latest_tags
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        echo tag=$(gh release list -R ${{ inputs.upstream_repo }} -L 1 | awk '{ print $1 }') >> $GITHUB_OUTPUT
        echo previous_tag=$(gh release list -R ${{ inputs.upstream_repo }} -L 2 | tail -n 1 | awk '{ print $1 }') >> $GITHUB_OUTPUT
    - name: Fetch last base
      shell: bash
      run: |
        if (!git fetch origin tag ${{ inputs.base_tag }}); then
          datadog_head=$(git ls-remote --refs origin refs/heads/datadog | awk '{ print $1 }')
          git tag ${{ inputs.base_tag }} $(git merge-base $datadog_head ${{ steps.get_latest_tags.previous_tag }})
        fi
    - name: Fetch datadog branch
      shell: bash
      run: git fetch origin  ${{ inputs.datadog_branch }}
    - name: Checkout datadog branch
      shell: bash
      run: git checkout ${{ inputs.datadog_branch }}
    - name: Rebase datadog branch
      shell: bash
      run: git rebase --onto ${{ steps.get_latest_tags.outputs.tag }} ${{ inputs.base_tag }}
    - name: Push datadog branch
      shell: bash
      run: git push -f origin ${{ inputs.datadog_branch }}
    - name: Tag release
      shell: bash
      run: git tag ${{ steps.get_latest_tag.outputs.tag }}-dd ${{ inputs.datadog_branch }}
    - name: Push tag
      shell: bash
      run: git push origin ${{ steps.get_latest_tags.outputs.tag }}-dd
    - name: Move last base tag
      shell: bash
      run: git tag -f ${{ inputs.base_tag }} ${{ steps.get_latest_tags.outputs.tag }}
    - name: Push last base tag
      shell: bash
      run: git push -f origin ${{ inputs.base_tag }}

branding:
  icon: 'package'
  color: 'purple'
